name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Test
        run: make test build